### ISSUE TITLE
OSX shortcut conflict – Cmd-M

### ISSUE THREAD

**Issue by shaneparsons** [redmunds/brackets-quick-markup#40]
**Cmd-M** is currently reserved for minimizing windows & applications on OSX.
Would you be able to use **Cmd-Shift-M** to toggle the mode and **Cmd-Option-M** to toggle help instead?

**Comment by shaneparsons** [comment]
I've actually fixed the issue in a forked version and it seems to work great..
How do I go about creating a pull request to merge with yours?

I'm fairly new to github..

**Comment by redmunds** [comment]
Thanks for contributing.

The easiest way is to go to the page on github: https://github.com/redmunds/brackets-quick-markup/blob/master/main.js

Click on pencil icon in upper-right to edit. Make change and Save. Github will create a pull request for you. Fill in description and click OK to submit.

**Comment by redmunds** [comment]
Let me know if you would rather learn how to do it from your forked repo and I can help you with that.

**Comment by shaneparsons** [comment]
I did it through my own forked repo..
I missed *bottom-panel.html* the first time but it's updated now as well.

**Comment by redmunds** [comment]
Fixed in https://github.com/redmunds/brackets-quick-markup/pull/42. Closing
