### ISSUE TITLE
Pressing the shortcuts are doing nothing for me

### ISSUE THREAD

**Issue by pstonier** [redmunds/brackets-quick-markup#43]
Pressing the shortcuts are doing nothing for me. I've been trying both control and command for shortcuts, but they simply aren't taking. I've removed all other extensions to avoid conflicts.

**Comment by redmunds** [comment]
> I've been trying both control and command for shortcuts...

Based on this statement, it sounds like you are on Mac. It's the `Cmd` key.

First you have to start Quick Mark "mode" (Edit > Quick Markup Mode). Note that shortcut used to be `Cmd+M`, but recently changed to `Cmd+Shift+M`. You should see a bar at bottom of editor to indicate that it's on.

Second, it only works on pages that Brackets considers HTML, so look at Language indicator on statusbar.

Third, `Cmd+Enter`, `Cmd+Delete`, and `Cmd+Backspace` only work inside tags.

Does that fix it?

**Comment by pstonier** [comment]
Thank you for the quick reply! I found what was causing the issue. I needed to wrap the content in an HTML tag. I was just editing content for a WordPress widget, so it wasn't wrapped to begin with.
