### ISSUE TITLE
Customize the bottom-panel 

### ISSUE THREAD

**Issue by pablonolla** [redmunds/brackets-quick-markup#44]
I've edit the .json file according to my needs, and it works just fine, but the bottom-panel only displays the "tagName", not the attribute, which would be more adequate, or a custom string of text, which would be great.

Editing the main.js on line 955 like this:

```js
   cellData.cells.push({key: id.toUpperCase(), tag: "<" + tag.attributes + ">"});
```

works, but then those shortcuts without attribute display as <undefined> in the panel.

**Comment by redmunds** [comment]
Fixed with #45. Closing.
