### ISSUE TITLE
shortcuts to admit nested tags...

### ISSUE THREAD

**Issue by pablonolla** [redmunds/brackets-quick-markup#47]
So far, a shortcut which should wrap a selected text in between `<span>` tags behaves incorrectly if the text is already inside a `<span>`: it deletes the previous `<span>`.

Also, a `<div>` shortcut, if applied to a text that is already inside a `<div>`, will not work at all.

**Comment by redmunds** [comment]
Fixed in version 3.3:

1. Fix same block-level tags to be nestable
2. Provide `nestable` property for defining nestable inline tags

**Comment by pablonolla** [comment]
Hi!
The first fix works well.. now you can nest a div inside another using a shortcut.
But as for the 2nd... How should I use the nestable property? how is the sintaxis, and where should i type it?
thank you!  and sorry for asking thingsthat probably are obvious for others.
p

**Comment by redmunds** [comment]
@pablonolla I added documentation to the [Configuration section of the README file](https://github.com/redmunds/brackets-quick-markup#configuration). Could you review that to make sure it makes sense? Thanks.

**Comment by pablonolla** [comment]
It makes a lot of sense , yes !
it's very clear.
again, thank you very very much.
you are making my work much more easy, productive and fun.
i wish i could contribute somehow...
all the best!
p


2015-09-04 18:01 GMT+02:00 Randy Edmunds <notifications@github.com>:

**Comment by redmunds** [comment]
Thanks

> i wish i could contribute somehow...

Your feedback helps.
